function [x, y, sensitive, training, test] = importBankData()
    ftoreadData = '+dataImport/bank-full.csv';
    fidData = fopen(ftoreadData);
    fgetl(fidData);
    data = textscan(fidData, '%f%s%s%s%s%f%s%s%s%f%s%f%f%f%f%s%s', 'Delimiter',';');

    data_f =[dataImport.convertToDouble(data(:,1)), ...
        dataImport.convertToValues(data(:,2)), ...
        dataImport.convertToValues(data(:,3)), ...
        dataImport.convertToValues(data(:,4)), ...
        dataImport.convertToValues(data(:,5)), ...
        dataImport.convertToDouble(data(:,6)), ...
        dataImport.convertToValues(data(:,7)), ...
        dataImport.convertToValues(data(:,8)), ...
        dataImport.convertToValues(data(:,9)), ...
        dataImport.convertToDouble(data(:,10)), ...
        dataImport.convertToValues(data(:,11)), ...
        dataImport.convertToDouble(data(:,12)), ...
        dataImport.convertToDouble(data(:,13)), ...
        dataImport.convertToDouble(data(:,14)), ...
        dataImport.convertToDouble(data(:,15)), ...
        dataImport.convertToValues(data(:,16))];

    a = data(:,17);
    a = vertcat(a{:});

    y = ones(size(data_f,1),1);
    for i=1:length(y)
        if(strcmp(cellstr(a(i)),'"no"')==1)
            y(i) = 0;
        end
    end
    
    sensitive = false(size(data_f,1), 1);
%    a = data(:,1);
    a = data(:,3);
    a = vertcat(a{:});
    for j=1:size(data_f,1)
%        sensitive(j) = double(a(j))>=25 & double(a(j))<=60;
        sensitive(j) = strcmp(cellstr(a(j)),'"divorced"')==1);
    end;
    
    x = data_f;

    %% generate training and test data
    training = randsample(1:length(y), round(length(y)*0.7));
    test = setdiff(1:length(y), training);
end
